#!/usr/bin/python
import os,sys

help="""
    Usage:
    sdled (without options) - display all sd* devices status
    sdled /dev/sd[letter] - display status of requested device
    sdled /dev/sd[letter] faulty - set led indicator to 'faulty' 
                          this WILL NOT make device faulty, just set 
                          enclosure led to 'FAULTY' status.
    sdled /dev/sd[letter] locate - set led indicator to 'locate' status
"""

def sd_list():
    """
    return list of all sd devices in /sys/block
    """
    return filter(lambda x: "sd" in x, os.listdir("/sys/block"))

def get_status(dev):
    """
       return status ("N/A", "Off", "Faul", "Locate") for given device
    """
    enc="enclosure_device" #magik string to access enclosure data
    os.chdir("/sys/block/"+dev+"/device")
    l=filter(lambda x: enc in x, os.listdir("."))
    if not l:
        return "N/A" #No magic path, can't get status
    try:
        os.chdir(l[0])
        fault=int(file("fault",'r').readline())
        locate=int(file("locate",'r').readline())
        if(fault):
            return "Fault"
        if(locate):
            return "Locate"
        return "Off"
    except:
        return "N/A" #any error means we can't get status


if len(sys.argv)<2:
    print "DEVICE NAME      STATUS"
    for a in sd_list():
        print ("/dev/"+a).ljust(17),  get_status(a)
	sys.exit(0)
if len(sys.argv)<3:
    if sys.argv[1]=="--help" or sys.argv[1]=="-h":
        print help
        sys.exit(0)

